export const SET_ING = "SET_ING";
export const ADD_ING = "ADD_ING";
export const REMOVE_ING = "REMOVE_ING";
export const FETCH_ING_FAILED = "FETCH_ING_FAILED";
export const INITIALIZE_INGREDIENT="INITIALIZE_INGREDIENT";
// for order container
export const PURCHASE_BURGER_SUCCESS="PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED="PURCHASE_BURGER_FAILED";
export const PURCHASE_BURGER_START="PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";
// for handling the orders view
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED="FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_START="FETCH_ORDERS_START";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_INIT = "FETCH_INIT";
// for handling authentications
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT";
export const SET_AUTH_REDIRECT_PATH="SET_AUTH_REDIRECT_PATH";
export const AUTH_CHECK_LOGOUT = "AUTH_CHECK_LOGOUT";
export const AUTH_USER='AUTH_USER';
export const AUTH_CHECK_INTITIAL_LOGIN_STATE="AUTH_CHECK_INTITIAL_LOGIN_STATE";