export const SET_ING = "SET_ING";
export const ADD_ING = "ADD_ING";
export const REMOVE_ING = "REMOVE_ING";
export const FETCH_ING_FAILED = "FETCH_ING_FAILED";
// for order container
export const PURCHASE_BURGER_SUCCESS="PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED="PURCHASE_BURGER_FAILED";
export const PURCHASE_BURGER_START="PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";
// for handling the orders view
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED="FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_START="FETCH_ORDERS_START";
export const FETCH_ORDERS = "FETCH_ORDERS";
